
const data = {
    products: [
        {
            _id: '1',
            name: 'Tomato1',
            category: 'veg',
            image: '/assets/images/products/coconut.jpg',
            price: '20',
            brand: 'brandName',
            rating: 2,
            numreviews: 8,
            stock: 5,
            description: 'High quality tomato1',
        },
        {
            _id: '2',
            name: 'Tomato2',
            category: 'veg',
            image: '/assets/images/products/tomoto.jpg',
            price: '32',
            brand: '',
            rating: 3,
            numreviews: 6,
            stock: 5,
            description: 'High quality tomato2',
        },
        {
            _id: '3',
            name: 'Tomato3',
            category: 'veg',
            image: '/assets/images/products/caps.jpg',
            price: '10',
            brand: '',
            rating: 2.4,
            numreviews: 3,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '4',
            name: 'Tomato4',
            category: 'veg',
            image: '/assets/images/products/coli.jpg',
            price: '52',
            brand: '',
            rating: 2.9,
            numreviews: 4,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '5',
            name: 'Tomato5',
            category: 'veg',
            image: '/assets/images/products/tomoto.jpg',
            price: '50',
            brand: '',
            rating: 3.6,
            numreviews: 5,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '6',
            name: 'Tomato1',
            category: 'veg',
            image: '/assets/images/products/coconut.jpg',
            price: '20',
            brand: 'brandName',
            rating: 2,
            numreviews: 8,
            stock: 10,
            description: 'High quality tomato',
        },
        {
            _id: '7',
            name: 'Tomato2',
            category: 'veg',
            image: '/assets/images/products/tomoto.jpg',
            price: '32',
            brand: '',
            rating: 3,
            numreviews: 6,
            stock: 10,
            description: 'High quality tomato',
        },
        {
            _id: '8',
            name: 'Tomato3',
            category: 'veg',
            image: '/assets/images/products/caps.jpg',
            price: '10',
            brand: '',
            rating: 2.4,
            numreviews: 3,
            stock: 30,
            description: 'High quality tomato',
        },
        {
            _id: '9',
            name: 'Tomato4',
            category: 'veg',
            image: '/assets/images/products/coli.jpg',
            price: '52',
            brand: '',
            rating: 2.9,
            numreviews: 4,
            stock: 10,
            description: 'High quality tomato',
        },
        {
            _id: '10',
            name: 'Tomato5',
            category: 'veg',
            image: '/assets/images/products/tomoto.jpg',
            price: '50',
            brand: '',
            rating: 3.6,
            numreviews: 5,
            stock: 20,
            description: 'High quality tomato',
        },
        {
            _id: '11',
            name: 'Tomato1',
            category: 'veg',
            image: '/assets/images/products/coconut.jpg',
            price: '20',
            brand: 'brandName',
            rating: 2,
            numreviews: 8,
            stock: 6,
            description: 'High quality tomato',
        },
        {
            _id: '12',
            name: 'Tomato2',
            category: 'veg',
            image: '/assets/images/products/tomoto.jpg',
            price: '3212',
            brand: '',
            rating: 3,
            numreviews: 6,
            stock: 8,
            description: 'High quality tomato',
        },
        {
            _id: '13',
            name: 'Tomato3',
            category: 'veg',
            image: '/assets/images/products/caps.jpg',
            price: '10',
            brand: '',
            rating: 2.4,
            numreviews: 3,
            stock: 9,
            description: 'High quality tomato',
        },
        {
            _id: '14',
            name: 'Tomato4',
            category: 'veg',
            image: '/assets/images/products/coli.jpg',
            price: '52',
            brand: '',
            rating: 2.9,
            numreviews: 4,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '15',
            name: 'Tomato5',
            category: 'veg',
            image: '/assets/images/products/tomoto.jpg',
            price: '50',
            brand: '',
            rating: 3.6,
            numreviews: 5,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '16',
            name: 'Tomato1',
            category: 'veg',
            image: '/assets/images/products/coconut.jpg',
            price: '20',
            brand: 'brandName',
            rating: 2,
            numreviews: 8,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '17',
            name: 'Tomato2',
            category: 'veg',
            image: '/assets/images/products/tomoto.jpg',
            price: '32',
            brand: '',
            rating: 3,
            numreviews: 6,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '18',
            name: 'Tomato3',
            category: 'veg',
            image: '/assets/images/products/caps.jpg',
            price: '10',
            brand: '',
            rating: 2.4,
            numreviews: 3,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '19',
            name: 'Tomato4',
            category: 'veg',
            image: '/assets/images/products/coli.jpg',
            price: '52',
            brand: '',
            rating: 2.9,
            numreviews: 4,
            stock: 0,
            description: 'High quality tomato',
        },
        {
            _id: '20',
            name: 'Tomato5',
            category: 'veg',
            image: '/assets/images/products/tomoto.jpg',
            price: '50',
            brand: '',
            rating: 3.6,
            numreviews: 5,
            stock: 8,
            description: 'High quality tomato',
        },
    ],
};

export default data;